### ISSUE TITLE
Saving first profile loses "Use with sites" value

### ISSUE THREAD

**Issue by sunaku** [passwordmaker/chrome-passwordmaker#159] opened 2016-10-02 23:25 UTC
Saving the first profile in the "Profile List" causes the "Use with sites" value to become :scream: lost:

1. Click on first profile
2. Enter a domain name in "Use with sites" field
3. Click "Save" button
4. Click on a different profile
5. Click on first profile
6. Observe that "Use with sites" field is now blank

Thanks for your consideration.

**Comment by heavensrevenge** [comment] 2016-10-25 04:12
Oh this is by design, so it is a generic profile for use with ALL sites unless specified in a different profile.
The way this is used is to test the strength of the default profile with a certain website URL and to tweak settings to save into a different specific profile later.  But this is by design so it won't be fixed.

**Closed by heavensrevenge** 2016-10-25 04:12 UTC

**Comment by sunaku** [comment] 2016-10-25 04:39
Thanks for explaining: it makes sense :+1: but it's not an obvious thing to infer just by looking at the GUI. :cold_sweat:

How about disabling or hiding the "Use with sites" field _only in the first profile's editor_ GUI in order to make the _mechanism reflect the policy_?  :policeman:  That way, the user won't be mislead :scream: into thinking that the input they entered into that "Use with sites" field  was actually saved by the system, because that's what normally happens for all non-first profiles. :scream:  As it stands, the mechanism currently lies :speak_no_evil: to the user. :disappointed:
